name: LHCI-local
on: push
jobs:
  # This is a run that targets static files using static-dist-dir.
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse against a local server
        uses: ./
        with:
          configPath: '.github/lighthouse/lighthouserc-local-server.js'
